name: DendriticRewiring

channels:
    - defaults
    - bioconda

dependencies:
    - python=3.7
    - scoop=0.7
    - numpy=1.17
    - scipy=1.3
    - matplotlib=3.1
    - seaborn=0.9
    - networkx=2.4
    - ruamel_yaml=0.15
    - pip
    - pip:
        - mpi4py==3.0
